---
- hosts: all
  sudo: true

  vars:
    document_root: /vagrant/www
    db_name: milena
    db_user: root
    db_password: ''

  handlers:
    - name: reload Apache
      service: name=apache2 state=reloaded

  tasks:

    - name: update APT cache
      apt: update_cache=yes cache_valid_time=3600

    - name: install required packages
      apt: name={{ item }} state=present
      with_items:
        - apache2
        - libapache2-mod-php5
        - php5-cli
        - php5-mysql
        - mysql-server
        - python-mysqldb

    - name: configure Apache virtual host
      template:
        src=share/vhost.conf.j2
        dest=/etc/apache2/sites-available/000-default.conf
      notify:
        - reload Apache

    - name: install MySQL configuration files
      template:
        src=share/my.cnf.j2
        dest={{ item.dir }}/.my.cnf
        owner={{ item.owner }}
        group={{ item.owner }}
        mode=0600
      with_items:
        - { dir: /home/vagrant, owner: vagrant }
        - { dir: /root, owner: root }

    - name: create MySQL database '{{ db_name }}'
      mysql_db:
        name={{ db_name }}
        state=present
      register: db_created

    - name: import MySQL database dump
      mysql_db:
        name={{ db_name }}
        state=import
        target=/vagrant/share/dump.sql
      when: db_created.changed

    - name: configure application
      template:
        src=share/config.php.j2
        dest=/vagrant/config.php

    - name: build the application
      command: make
      args:
        chdir: /vagrant
      sudo: false
