---
- hosts: all
  sudo: true

  vars:
    document_root: /vagrant/www

  handlers:
    - name: reload Apache
      service: name=apache2 state=reloaded

  tasks:

    - name: update APT cache
      apt: update_cache=yes cache_valid_time=3600

    - name: install required packages
      apt: name={{ item }} state=present
      with_items:
        - apache2
        - libapache2-mod-php5
        - php5-cli
        - php5-mysql
        - mysql-server
        - python-mysqldb

    - name: configure default virtual host
      template:
        src=vhost.conf.j2
        dest=/etc/apache2/sites-available/000-default.conf
      notify:
        - reload Apache

    - name: install .my.cnf to vagrant user
      copy:
        src=my.cnf
        dest=/home/vagrant/.my.cnf
        mode=0600
        owner=vagrant
        group=vagrant

    - name: install .my.cnf to root user
      copy:
        src=my.cnf
        dest=/root/.my.cnf
        mode=0600
        owner=root
        group=root

    - name: create database milena
      mysql_db:
        name=milena
        state=present
      register: db_created

    - name: import database
      mysql_db:
        name=milena
        state=import
        target=/vagrant/share/authDB.sql
      when: db_created.changed

    - name: build application
      command: make
      args:
        chdir: /vagrant
      sudo: false
